import "./styles/theme.css";
import { navigate, initRouter, registerRoute } from "./router";
import { onAuthStateChange } from "./lib/auth";
import { initColorScheme } from "./lib/color-scheme";
import { bootBranding } from "./lib/theme";
import { renderLogin } from "./pages/login";
import { renderAdminDashboard } from "./pages/admin/dashboard";
import { renderAdminProperties } from "./pages/admin/properties";
import { renderAdminPropertyDetail } from "./pages/admin/property-detail";
import { renderAdminListings } from "./pages/admin/listings";
import { renderAdminListingDetail } from "./pages/admin/listing-detail";
import { renderAdminLeases } from "./pages/admin/leases";
import { renderAdminLeaseDetail } from "./pages/admin/lease-detail";
import { renderAdminPayments } from "./pages/admin/payments";
import { renderAdminDocuments } from "./pages/admin/documents";
import { renderAdminMaintenance } from "./pages/admin/maintenance";
import { renderAdminMaintenanceDetail } from "./pages/admin/maintenance-detail";
import { renderAdminTenants } from "./pages/admin/tenants";
import { renderAdminTenantDetail } from "./pages/admin/tenant-detail";
import { renderAdminOwners } from "./pages/admin/owners";
import { renderAdminOwnerDetail } from "./pages/admin/owner-detail";
import { renderAdminSettings } from "./pages/admin/settings";
import { renderAdminContacts } from "./pages/admin/contacts";
import { renderOwnerDashboard } from "./pages/owner/dashboard";
import { renderOwnerProperties } from "./pages/owner/properties";
import { renderOwnerPropertyDetail } from "./pages/owner/property-detail";
import { renderOwnerPayments } from "./pages/owner/payments";
import { renderOwnerDocuments } from "./pages/owner/documents";
import { renderTenantDashboard } from "./pages/tenant/dashboard";
import { renderTenantLease } from "./pages/tenant/lease";
import { renderTenantPayments } from "./pages/tenant/payments";
import { renderTenantDocuments } from "./pages/tenant/documents";
import { renderTenantMaintenance } from "./pages/tenant/maintenance";
import { renderTenantMaintenanceDetail } from "./pages/tenant/maintenance-detail";

initColorScheme();
await bootBranding();

registerRoute({ path: "/login", roles: "public", render: renderLogin });
registerRoute({ path: "/admin", roles: ["admin", "agent"], render: renderAdminDashboard });
registerRoute({ path: "/admin/properties", roles: ["admin", "agent"], render: renderAdminProperties });
registerRoute({ path: "/admin/properties/:id", roles: ["admin", "agent"], render: renderAdminPropertyDetail });
registerRoute({ path: "/admin/listings", roles: ["admin", "agent"], render: renderAdminListings });
registerRoute({ path: "/admin/listings/:id", roles: ["admin", "agent"], render: renderAdminListingDetail });
registerRoute({ path: "/admin/leases", roles: ["admin", "agent"], render: renderAdminLeases });
registerRoute({ path: "/admin/leases/:id", roles: ["admin", "agent"], render: renderAdminLeaseDetail });
registerRoute({ path: "/admin/payments", roles: ["admin", "agent"], render: renderAdminPayments });
registerRoute({ path: "/admin/documents", roles: ["admin", "agent"], render: renderAdminDocuments });
registerRoute({ path: "/admin/maintenance", roles: ["admin", "agent"], render: renderAdminMaintenance });
registerRoute({ path: "/admin/maintenance/:id", roles: ["admin", "agent"], render: renderAdminMaintenanceDetail });
registerRoute({ path: "/admin/tenants", roles: ["admin", "agent"], render: renderAdminTenants });
registerRoute({ path: "/admin/tenants/:id", roles: ["admin", "agent"], render: renderAdminTenantDetail });
registerRoute({ path: "/admin/owners", roles: ["admin", "agent"], render: renderAdminOwners });
registerRoute({ path: "/admin/owners/:id", roles: ["admin", "agent"], render: renderAdminOwnerDetail });
registerRoute({ path: "/admin/settings", roles: ["admin"], render: renderAdminSettings });
registerRoute({ path: "/admin/vendors", roles: ["admin", "agent"], render: renderAdminContacts });
registerRoute({ path: "/owner", roles: ["owner"], entitlement: "portal.owner", render: renderOwnerDashboard });
registerRoute({ path: "/owner/properties", roles: ["owner"], entitlement: "portal.owner", render: renderOwnerProperties });
registerRoute({ path: "/owner/properties/:id", roles: ["owner"], entitlement: "portal.owner", render: renderOwnerPropertyDetail });
registerRoute({ path: "/owner/payments", roles: ["owner"], entitlement: "portal.owner", render: renderOwnerPayments });
registerRoute({ path: "/owner/documents", roles: ["owner"], entitlement: "portal.owner", render: renderOwnerDocuments });
registerRoute({ path: "/tenant", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantDashboard });
registerRoute({ path: "/tenant/lease", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantLease });
registerRoute({ path: "/tenant/payments", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantPayments });
registerRoute({ path: "/tenant/documents", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantDocuments });
registerRoute({ path: "/tenant/maintenance", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantMaintenance });
registerRoute({ path: "/tenant/maintenance/:id", roles: ["tenant"], entitlement: "portal.tenant", render: renderTenantMaintenanceDetail });

onAuthStateChange((session) => {
  if (!session) navigate("/login", { replace: true });
});

initRouter();
